metadata:
- dataId: chronic-ai-prompts.yaml
  group: DEFAULT_GROUP
  type: yaml
- dataId: chronic-common.yaml
  group: DEFAULT_GROUP
  type: yaml
- dataId: chronic-common-oss.yaml
  group: DEFAULT_GROUP
  type: yaml
- dataId: chronic-common-redis.yaml
  group: DEFAULT_GROUP
  type: yaml
- dataId: chronic-common-security.yaml
  group: DEFAULT_GROUP
  type: yaml
- dataId: chronic-common-service.yaml
  group: DEFAULT_GROUP
  type: yaml
- dataId: chronic-gateway.yaml
  group: DEFAULT_GROUP
  type: yaml
- dataId: chronic-points-service.yaml
  group: DEFAULT_GROUP
  type: yaml
- dataId: chronic-shop-service.yaml
  group: DEFAULT_GROUP
  type: yaml
- dataId: chronic-user-service.yaml
  group: DEFAULT_GROUP
  type: yaml
